Задача 1\
Даны значения величины заработной платы заемщиков банка (zp) и значения их
поведенческого кредитного скоринга (ks): \
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],\
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].\
Используя математические
операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату
(то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая
переменная). Произвести расчет как с использованием intercept, так и без

In [154]:
import numpy as np
import math

In [155]:
x = np.array ([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array ([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
n = 10

In [156]:
b1 = (np.mean(x*y)-np.mean(y)*np.mean(x))/np.mean(pow(x,2)-pow(np.mean(x),2))
b1

2.620538882402764

In [157]:
b0 = np.mean(y) - b1*np.mean(x)
b0

444.1773573243597

In [158]:
y_pred_array = []
for i in range(len(x)):
    y_pred = b0 + b1 * x[i]
    y_pred_array.append(y_pred)
print(y_pred_array)

[535.8962182084565, 562.1016070324841, 942.0797449808849, 968.2851338049126, 548.9989126204703, 627.6150790925532, 585.686456974109, 837.2581896847744, 758.6420232126914, 732.4366343886638]


С использованием intercept

In [159]:
from sklearn.linear_model import LinearRegression

In [160]:
model = LinearRegression()

In [161]:
x = x.reshape(-1,1)
x

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [162]:
regres = model.fit(x,y)
print(regres.intercept_)

444.17735732435943


In [163]:
print(regres.coef_)

[2.62053888]


Задача 2 \
Посчитать коэффициент линейной регрессии при заработной плате (zp), используя
градиентный спуск (без intercept).

In [164]:
def mse_(B1, y = y, x = x, n = 10):
    return pow(np.sum(B1*x - y),2)/n

In [165]:
alpha = 1e-6


In [166]:
B1 = 1
n = 10
for i in range(3000):
    B1 -= alpha*(2/n)* np.sum((B1*x-y)*x)
    if i % 500==0:
        print (f'iteration num: {i} B1 value: {B1} mse value: {mse_(B1)}')

iteration num: 0 B1 value: 2.1641452 mse value: 240546770.82687306
iteration num: 500 B1 value: 5.225081660206436 mse value: 32427624.961729746
iteration num: 1000 B1 value: 5.225081660206436 mse value: 32427624.961729746
iteration num: 1500 B1 value: 5.225081660206436 mse value: 32427624.961729746
iteration num: 2000 B1 value: 5.225081660206436 mse value: 32427624.961729746
iteration num: 2500 B1 value: 5.225081660206436 mse value: 32427624.961729746


In [167]:
mse_(5.22508)

32427685.591764547

 3 (Дополнительно) Произвести вычисления как в пункте 2, но с вычислением intercept. Учесть, что
изменение коэффициентов должно производиться
на каждом шаге одновременно (то есть изменение одного коэффициента не должно
влиять на изменение другого во время одной итерации).

In [169]:
x

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [170]:
y = y.reshape((10,1))
y

array([[401],
       [574],
       [874],
       [919],
       [459],
       [739],
       [653],
       [902],
       [746],
       [832]])

In [171]:
X = np.hstack([np.ones((10, 1)),x])
X

array([[  1.,  35.],
       [  1.,  45.],
       [  1., 190.],
       [  1., 200.],
       [  1.,  40.],
       [  1.,  70.],
       [  1.,  54.],
       [  1., 150.],
       [  1., 120.],
       [  1., 110.]])

In [172]:
B = np.dot(np.linalg.inv(np.dot(X.T, X)), X.T @y)
B

array([[444.17735732],
       [  2.62053888]])